### ISSUE TITLE
Rendering the Notification on my blade file

### ISSUE THREAD

**Issue by horlathunbhosun** [php-flasher/flasher#3]
I was trying to render the ` {{ flasher_render() }}` on my blade but i keep getting an error like the image bellow
![image](https://user-images.githubusercontent.com/25985738/118351873-4b4bb600-b556-11eb-850a-0af83c851cc9.png)
thanks

**Comment by horlathunbhosun** [comment]
![image](https://user-images.githubusercontent.com/25985738/118351964-c0b78680-b556-11eb-8e99-3782492fb212.png)

**Comment by yoeunes** [comment]
hello sir apparently you are using laravel not symfony so please try this syntax and give me your feedback 

@flasher_render

**Comment by horlathunbhosun** [comment]
Aright Thanks  resolved

**Comment by yoeunes** [comment]
cool glade that its works
