### ISSUE TITLE
I don't know how to use it...

### ISSUE THREAD

**Issue by ItsWidee** [php-flasher/flasher#4]
Hello !

I am trying to create a login system with notifications if the connection is successful or not. My website being in PHP and because I wanted to use Toastr, I discovered PHPFlasher. Unfortunately, I'm still a beginner, and I'm a bit confused by the documentation. I successfully installed the package using composer, but I can't make it work.
I take the ToastrFactory instance and I put it in a file named `notifications.php`. So I have that : 
```php
<?php

namespace App\Controller;

use Flasher\Toastr\Prime\ToastrFactory;

class NotifyController
{
	public function flasher(ToastrFactory $flasher)
	{
		// ... 
		$flasher->addSuccess('Data has been saved successfully!');

		// ... redirect or render a view here
	}
} ?>
```

I do a `require` in the login page, and after I don't know how to use it...

So, can someone help me ? ^^

**Comment by yoeunes** [comment]
Hello @ItsWidee, thanks for using this package, I really don't have time to document all parts of this library.
do you have any github repository on which i can help you using this library.
this is my personal email : younes.khoubza@gmail.com

**Comment by yoeunes** [comment]
are you using a Framework like Symfony or Laravel or Plain PHP project ?

**Comment by ItsWidee** [comment]
Hello @yoeunes, thank you for the quick answer.

I'm using plain PHP. Unfortunately, I can't share you all the code, as it is still personal. But I can share the codes of the login and notification pages.

notifications.php :
```php
<?php

namespace App\Controller;

use Flasher\Toastr\Prime\ToastrFactory;

class NotifyController
{
	public function flasher(ToastrFactory $flasher)
	{
		// ... 
		$flasher->addSuccess('Data has been saved successfully!');

		// ... redirect or render a view here
	}
} ?>
```

login.php :
```php
<?php require_once 'includes/needed.php';
require_once 'includes/db.php';

if (isset($_SESSION['auth'])) {
    header('Location: account.php');
}

if (!empty($_POST['pseudo']) && !empty($_POST['mdp'])) {
    require_once 'includes/db.php';
    $req = $pdo->prepare('SELECT * FROM users WHERE (username = :username OR email = :username) AND (confirmed_at IS NOT NULL AND is_confirmed = 1)');
    $req->execute(['username' => $_POST['pseudo']]);
    $user = $req->fetch();
    if ($user) {
        if (password_verify($_POST['mdp'], $user['password'])) {
            if ($_POST['remember']) {
                $remember_token = str_random(250);
                $pdo->prepare('UPDATE users SET remember_token = ? WHERE id = ?')->execute([$remember_token, $user['id']]);
                setcookie('remember', $user['id'] . '==' . $remember_token . sha1($user['id'] . 'ratonlaveurs'), time() + 60 * 60 * 24 * 7);
                $_SESSION['auth'] = $user;
                // success notifications THEN redirection w/ header
            } else {
                $_SESSION['auth'] = $user;
                // success notifications THEN redirection w/ header
            }
        } else {
           // error notifications
        }
    } else {
       // error notifications
    }
}

?>
//There's HTML after
```

needed.php :
```php
<?php

session_set_cookie_params(["SameSite" => "Strict"]); //none, lax, strict
session_set_cookie_params(["Secure" => "true"]); //false, true
session_set_cookie_params(["HttpOnly" => "true"]); //false, true
session_start(); //everything before this

if (session_status() == PHP_SESSION_NONE) {
    session_start();
}
require_once 'functions.php';

//reconnect_from_cookie();

require_once 'vendor/autoload.php';

?>
<!-- Inclusion de scripts -->
<script src="/ressources/scripts/jquery/jquery.min.js"></script>
<script src="/ressources/scripts/toastr/toastr.min.js"></script>
<script src="/ressources/scripts/options.js"></script>

<?php require 'includes/notifications.php'; ?>
```

Here's the important files. In the condition in the login file, as the comments said, I want to put the toastr notifications using flasher, but I don't know how to do it...

**Comment by yoeunes** [comment]
hi @ItsWidee OK, i'll look at it in a moment

**Comment by ItsWidee** [comment]
No problem ! Take your time ^^

**Comment by yoeunes** [comment]
Hello again, you can take a look at this demo : 

https://github.com/yoeunes/plain-php-flasher-demo

if you have any questions let me know ^^

**Comment by ItsWidee** [comment]
Thanks a lot !!!
It works perfectly fine !
But I have a question : can I send the notification to another page ? After my user is successfully connected, I want to show him a notification in the account page. I've tried to create the builder in the login page then to render in the account page, but it doesn't work.

**Comment by yoeunes** [comment]
hello @ItsWidee  I just pushed the new code, to render the notification after redirection, check it out
and tell me if it works for you

**Comment by ItsWidee** [comment]
Oh, I find the problem.
So, I tried to put this code in my code, and it doesn't work. I found the problem : I execute the renderer in all my pages, so if a notification is waiting, it is executed. The thing is that all the PHP code is executed, so it does a redirection, but it thinks it has already executed the notification. So when it arrives in the account file, the code doesn't render the notification.
Is there a way to correct this ?

**Comment by yoeunes** [comment]
did you try to put exit; after the redirection code ?

```php
header('Location: /account.php');
exit();
````

**Comment by ItsWidee** [comment]
Oh ! It seems to work, but I now have a fatal error that... I can't really understand...

`Fatal error: Uncaught TypeError: Argument 1 passed to Flasher\Prime\Filter\FilterBuilder::Flasher\Prime\Filter\{closure}() must be an instance of Flasher\Prime\Envelope, instance of __PHP_Incomplete_Class given in D:\wamp64\www\StoryShare\new\vendor\php-flasher\flasher\Filter\FilterBuilder.php on line 75`

**Comment by yoeunes** [comment]
if you take a look at this file : https://github.com/yoeunes/plain-php-flasher-demo/blob/main/includes/init.php

```php
include_once __DIR__ . '/flasher.php';

if (session_status() == PHP_SESSION_NONE) {    
    session_start();
}
```

```session_start()``` should be declared after including the ```flasher.php``` that will resolve the problem

**Comment by ItsWidee** [comment]
That is perfect, It works perfectly fine. I'm going to close this issue, because everything works now !

Thanks a lot for your help and for creating this PHP package !

Have a great day !

**Comment by yoeunes** [comment]
hello @ItsWidee thanks for your feedback,
Bonne journée à toi également ^^.
