### ISSUE TITLE
Livewire

### ISSUE THREAD

**Issue by MuhamadSelim** [php-flasher/flasher#5]
Hello,
First Thanks a lot for this great Package , I'm really happy to find it, thanks for your efforts 
Is it possible to render the notification on livewire.
It is working great when redirecting but not on same page

**Comment by yoeunes** [comment]
Hello @MuhamadSelim I really appreciate your kind words thanks,
I have never used Livewire before.
But can you share a working code with Flasher ?

**Comment by MuhamadSelim** [comment]
[](https://github.com/jantinnerezo/livewire-alert)
I'm trying to make it , 
you can check attached project that implement sweet alert on livewire

**Comment by MuhamadSelim** [comment]
I'm trying to make it ,
you can check attached project that implement sweet alert on livewire
[https://github.com/jantinnerezo/livewire-alert](https://github.com/jantinnerezo/livewire-alert)

**Comment by MuhamadSelim** [comment]
In case any one came here you can use livewire dispatchBrowserEvent like below
`PHP $messages = json_encode(app('flasher.response_manager')->render(array(),'array'));
        $this->dispatchBrowserEvent('flasher-message',['data'=>$messages]);`
then in your view

`<script src="https://cdn.jsdelivr.net/npm/@flasher/flasher@0.1.3/dist/flasher.min.js"></script>
<script>
window.addEventListener('flasher-message', event => {
        const data = JSON.parse(event.detail.data)
        Flasher.getInstance().render(data);
    });
</script>`

**Comment by yoeunes** [comment]
Greate Job @MuhamadSelim , thank youuuu

**Comment by yoeunes** [comment]
did you create a package for it ?

**Comment by MuhamadSelim** [comment]
Not yet , but I'm planning for.

**Comment by yoeunes** [comment]
hello @MuhamadSelim you can find a livewire integration with php-flasher here: https://github.com/php-flasher/flasher-livewire .
and maybe if you have sometimes, if you could test it and tell me what's your thoughts about it.
