### ISSUE TITLE
Half of the notification covered by top navbar

### ISSUE THREAD

**Issue by VTrace** [php-flasher/flasher#6]
Hallo sir, I do really love all your works, I've used toastr and notify before and it always works very great for me. But with this php-flasher, I found a problem when I use laravel and adminlte template, half of the notification is covered by top navbar, as shown below:

![image](https://user-images.githubusercontent.com/25096564/131426346-87f41da1-cd34-42c8-a856-a2093fce5cfd.png)

Do you have any solution for that?

**Comment by yoeunes** [comment]
Hello @VTrace  thanks for your kind words , i appreciate it  🙏 .
i will try to see what i can do to solve this issue, maybe i will to add some z-index.

**Comment by VTrace** [comment]
Hi @yoeunes , thank you for your reply, I will be waiting for your latest update then.

**Comment by yoeunes** [comment]
Hello again, can you please upgrade to v0.4.17 or update your root_script configuration to : `https://cdn.jsdelivr.net/npm/@flasher/flasher@0.1.8/dist/flasher.min.js`

![Screenshot from 2021-08-31 03-05-28](https://user-images.githubusercontent.com/10859693/131429890-ba5dadcf-879f-4be9-bf0b-76f73ba2e5d1.png)

**Comment by VTrace** [comment]
Okay, it works great now.

![image](https://user-images.githubusercontent.com/25096564/131430220-93fdc989-5352-4af6-add2-dee25186952a.png)

Thanks a lot sir 🙏🙏🙏

**Comment by yoeunes** [comment]
you're welcome @VTrace
