### ISSUE TITLE
Call to undefined function App\Http\Controllers\toastr() or sweetAlert()

### ISSUE THREAD

**Issue by codenashwan** [php-flasher/flasher#7]
hello iam using livewire 2.x and laravel 8.5

i install flasher step by step like this

1 :  `composer require php-flasher/flasher-livewire`

2 : add  `Flasher\Livewire\FlasherLivewireServiceProvider::class,`  to providers in app.php

3 : add two renders method in  app.blade.php
```
<head>
    @livewireStyles
</head>
<body>
    @yield('content')
    @flasher_render
    @flasher_livewire_render
    @livewireScripts
    </body>
```

4 : Controllers

```
<?php
namespace App\Http\Controllers;
use Livewire\Component;
class Adddoctor extends Component
{
    public function submit(){
        sweetAlert()->livewire()->addInfo('notification using sweetalert library');
        // toastr()->livewire()->addSuccess('notification using toastr library');
    }

    public function render()
    {
        return view('adddoctor')->extends('layouts.app');
    }
} 
```

5 : when click a submit button output says 
`Call to undefined function App\Http\Controllers\toastr() or sweetAlert()`

**Comment by yoeunes** [comment]
Hello @codenashwan thanks for using flasher, you're doing the right thing, you just need to require the `toastr` or `sweet alert `libraries of both for laravel : 

```bash
composer require php-flasher/flasher-toastr-laravel
composer require php-flasher/flasher-sweet-alert-laravel
```
